// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestWebApi;

#nullable disable

namespace TestWebApi.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TestWebApi.Test", b =>
                {
                    b.Property<string>("column1")
                        .HasColumnType("varchar(255)")
                        .HasComment("테스트 코멘트1");

                    b.Property<string>("column2")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("테스트 코멘트2");

                    b.HasKey("column1");

                    b.ToTable("Tests", t =>
                        {
                            t.HasComment("테스트");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
